# Generated by Django 5.2.5 on 2025-08-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
