# Generated by Django 5.2.5 on 2025-08-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_artwork_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='object_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
